name: Release Patch
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-22.04
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN}}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: true
  linuxamd64build:
    name: build patch amd64 version
    needs: release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: build linux amd64 version
        run: |
          CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o patch-release -v main.go
          mkdir patch
          cp patch-release patch/patch-release
          cp patch.service patch/patch.service
          cp patch.sh patch/patch.sh
          cd patch
          mv patch-release patch

      - name: package
        run: tar -zcvf patch-linux-amd64.tar.gz patch
      - name: upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN}}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: patch-linux-amd64.tar.gz
          asset_name: patch-linux-amd64.tar.gz
          asset_content_type: application/gzip
  linuxarm64build:
    name: build patch arm64 version
    needs: release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: build linux arm64 version
        run: |
          sudo apt-get update
          sudo apt install gcc-aarch64-linux-gnu
          CGO_ENABLED=1 GOOS=linux GOARCH=arm64 CC=aarch64-linux-gnu-gcc go build -o patch-release -v main.go
          mkdir patch
          cp patch-release patch/patch-release
          cp patch.service patch/patch.service
          cp patch.sh patch/patch.sh
          cd patch
          mv patch-release patch

      - name: package
        run: tar -zcvf patch-linux-arm64.tar.gz patch
      - name: upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN}}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: patch-linux-arm64.tar.gz
          asset_name: patch-linux-arm64.tar.gz
          asset_content_type: application/gzip
  linuxs390xbuild:
    name: build patch s390x version
    needs: release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: build linux s390x version
        run: |
          sudo apt-get update
          sudo apt install gcc-s390x-linux-gnu -y
          CGO_ENABLED=1 GOOS=linux GOARCH=s390x CC=s390x-linux-gnu-gcc go build -o patch-release -v main.go
          mkdir patch
          cp patch-release patch/patch-release
          cp patch.service patch/patch.service
          cp patch.sh patch/patch.sh
          cd patch
          mv patch-release patch

      - name: package
        run: tar -zcvf patch-linux-s390x.tar.gz patch
      - name: upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN}}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: patch-linux-s390x.tar.gz
          asset_name: patch-linux-s390x.tar.gz
          asset_content_type: application/gzip